### PR TITLE
Added website branding

### LINKED ISSUE #46: feature/add-website-branding
## User Story: (2 points)
As a user I want to be able to recognize what website I am visiting via website branding.

## Brief Description
Adding website branding, like logo, title, and meta tags

## Feature Requirements
- Add logo
- Change website title
- Change meta description
- Remove boilerplate defaults
   - Default README.md from create-react-app

# Additional context
SEO and web hosting may be considered at a later date. This is just to remove default files and text leftover from initial setup.

### PR DESCRIPTION
**Pull request by Adamo-O**
## Brief Description
Added website branding

## Linked Issues
- closes #46 

## Changes
- Changed website title to "Bobble"
- Added favicon for browser logo
- Added logo for mobile icons
- Added meta description
- Added meta author
- Removed unnecessary comments
- Changed website theme color

### CODE REVIEW

**Review by aspyridakos — APPROVED** [review]

**Comment by Adamo-O** [comment]
Just rebased and added the icons to the website. Should be good to go!

**Review by emma-amar — COMMENTED** [review]
YA ! yay branding :-) looks good!

**Review by emma-amar — APPROVED** [review]
update: forgot to hit approve! looks good !

**Review by aspyridakos — APPROVED** [review]
Nice! 💯

**Pull request merged**
