### PR TITLE
Refresh items in cart cookies according to active products

### LINKED ISSUE #115: feature/refresh-cart-cookie
## User Story: (1 point)
As a user I want to be able to view only purchasable items in my cart.

## Brief Description
Refresh cart cookie according to products in the backend.

## Feature Requirements
- Refresh user cart cookie
- GET all items and filter out cart cookie according to available products

### PR DESCRIPTION
**Pull request by Adamo-O**
## Brief Description
Refresh cart according to items in the backend.

## Linked Issues
- closes #115 

## Changes
- Added `useEffect()` hook to refresh user cart cookie when they enter the cart page

### CODE REVIEW

**Review by emma-amar — DISMISSED** [review]
looks good !!!!!

**Review by aspyridakos — CHANGES_REQUESTED** [review]
Quantity buttons in cart don't work anymore.

**Comment by aspyridakos** [comment]
Edit: quantity and remove buttons don't work

**Comment by Adamo-O** [comment]
Just fixed the quantity buttons issue. I caused a `useEffect` loop whenever the cookies changed, which affected the item quantities and created 10 API requests per second! All is resolved now.

**Review by aspyridakos — DISMISSED** [review]
Nice! 👍

**Review by aspyridakos — APPROVED** [review]
Yay!! Looks great!

**Pull request merged**
