### PR TITLE
Seller specific product page

### LINKED ISSUE #117: feature/seller-page-specific-seller-products
## Brief Description
Ex: Home page for online shopping website

## Feature Requirements
- Only show products according to specific seller in user cookie
- Ensure admin can access all seller products

### PR DESCRIPTION
**Pull request by Adamo-O**
## Brief Description
Only show seller products according to logged in seller.

## Linked Issues
- closes #117 

## Changes
- Added conditional button rendering for admin
- Use user cookie to read seller id and GET all products sold by that seller
- Added table heading specifying selected seller's seller name

### CODE REVIEW

**Review by emma-amar — DISMISSED** [review]
looks great!!!

**Review by KooshaG — DISMISSED** [review]
This code was definitely written by a very smart cookie! 🍪🍪

**Review by aspyridakos — DISMISSED** [review]
This is awesome to see sellers up and running fully! I added some minor css stuff but otherwise look great 🚀

**Review by KooshaG — APPROVED** [review]
I have never seen more beautiful code in my whole life 🥲🥲

**Pull request merged**
