### PR TITLE
Feature/product-details-refactoring

### LINKED ISSUE #48: feature/product-view-more-page
## User Story: (4 points)
As a user I want to be able to access a more detailed product page when clicking on each product box in the product grid because I want to view more of the product info and be able to add the product to my cart.

## Brief Description
Full page product view which includes additional and more detailed product info than the product grid boxes. This page should include an option to add to cart, select quantities, and view product descriptions.

## Feature Requirements
- [x] Back button to navigate back to product grid
- [x] Add to cart button
- [x] Price, description (consider adding a expandable dropdown for this), brand, seller info, etc. (display all available product details)
- [x] Quantity buttons (+/-)
- [x] Product image taking up most of the page
- [ ] View cart link and added product info in alert once "add to cart" has been clicked (_optional_)

### PR DESCRIPTION
**Pull request by aspyridakos**
## Brief Description
Refactoring product-details page to condense and simplify code for URL linking.

## Linked Issues
- fixes #48 

## Changes
- fixes URL parsing to work with ids and display product name simultaneously

### CODE REVIEW

**Review by emma-amar — APPROVED** [review]
looks good !! i don’t think anything needs to be changed :-)

**Review by jungsoolee1 — APPROVED** [review]
Reviewed and looks good! Pretty cool how you deleted a big chunk and simplified it to one line.

**Review by Adamo-O — APPROVED** [review]
Good stuff! Clean code ftw

**Review by KooshaG — APPROVED** [review]
Looks all good and dandy 🤠

**Review by ricks021 — APPROVED** [review]
Looks good!

**Pull request merged**
