### PR TITLE
Browsing style changes and refactoring

### LINKED ISSUE #168: refactoring/browsing-style-changes
## Describe the refactor
Make SideNav responsive, fix various style issues.

## Changes
- Make SideNav filters full width
- Ensure SideNav is responsive at all sizes
- Consider different website background colour

### PR DESCRIPTION
**Pull request by Adamo-O**
## Brief Description
Created responsive SideNav with full width filters, and other style changes.

## Linked Issues
- closes #168 

## Changes
- Added Card around SideNav
- Made SearchBar, PriceFilter, and Dropdowns full width
- SearchBar can be styled via `style` prop
   - Used in SideNav to make text and border white
- Changed Grid sizing for ProductPage (SideNav and ProductGrid)
- Removed `!important` expressions from App.css
- Changed background colour to introduce pink to the white, and avoid eye strain from pure white

### CODE REVIEW

**Review by jungsoolee1 — APPROVED** [review]
It looks great! It is responsive on my end.

I'm a little confused as to your "Brief Description" of the pull request. Did you change the navbar too or only the sidenav?

**Comment by Adamo-O** [comment]
> It looks great! It is responsive on my end. It should be good to merge after resolving the merge conflicts.
> 
> I'm a little confused as to your "Brief Description" of the pull request. Did you change the navbar too or only the sidenav?

I meant SideNav sorry! Just fixed it.

**Review by aspyridakos — APPROVED** [review]
Looks great! Just one little suggestion to fix, when a user types in the search bar the text is white by the little "x" inside the search box is still blue and should probably be white or pink instead.

**Comment by aspyridakos** [comment]
> Looks great! Just one little suggestion to fix, when a user types in the search bar the text is white by the little "x" inside the search box is still blue and should probably be white or pink instead.

Ping me to re-approve if you decide to apply this fix :)

**Comment by aspyridakos** [comment]
Question:

Why did we opt to use inline style and JSX embedded CSS styling instead of using CSS classes?

**Comment by Adamo-O** [comment]
> Question:
> 
> Why did we opt to use inline style and JSX embedded CSS styling instead of using CSS classes?

For the search bar? Two main reasons:
1. We wanted the search bar to be generic. By using CSS classes, we wouldn't be able to do that. 
   a. By using CSS classes to change the elements, they would look the same for both instances of SearchBar (in SideNav and in ViewOrders). For example, if we make a CSS class to turn the borders and text white, that would also show up on ViewOrders, which ruins the point.
   b. If, when rendering the SearchBar component, we add `className=X` as a prop, and we have different classes for different uses of the SearchBar, that wouldn't style correctly. That's because we want to target a *specific* element **within** the SearchBar, and not style the whole search bar itself.
   Therefore, we decided to make a `style` prop and allow the creator of the SearchBar instance to decide how to style it.
2. JSX embedded `sx` styles are recommended by MUI, and will ensure precedence over CSS classes. 
   While the precedence issue was solved by removing the `!important` tags on previous CSS classes, this is still best practices, and allowed for reason 1 to occur.

**Comment by aspyridakos** [comment]
> > Question:
> > Why did we opt to use inline style and JSX embedded CSS styling instead of using CSS classes?
> 
> For the search bar? Two main reasons:
> 
> 1. We wanted the search bar to be generic. By using CSS classes, we wouldn't be able to do that.
>    
>    1. By using CSS classes to change the elements, they would look the same for both instances of SearchBar (in SideNav and in ViewOrders). For example, if we make a CSS class to turn the borders and text white, that would also show up on ViewOrders, which ruins the point.
>    2. If, when rendering the SearchBar component, we add `className=X` as a prop, and we have different classes for different uses of the SearchBar, that wouldn't style correctly. That's because we want to target a _specific_ element **within** the SearchBar, and not style the whole search bar itself.
>    3. Therefore, we decided to make a `style` prop and allow the creator of the SearchBar instance to decide how to style it.
> 2. JSX embedded `sx` styles are recommended by MUI, and will ensure precedence over CSS classes.
>    While the precedence issue was solved by removing the `!important` tags on previous CSS classes, this is still best practices, and allowed for reason 1 to occur.

That  makes a lot of sense, thanks for the clarification!

**Comment by aspyridakos** [comment]
Awesome job with the search bar! It looks fantastic😎

**Pull request merged**
