### PR TITLE
feature/seller-products-page

### LINKED ISSUE #57: feature/sellers-product-form
## User Story: (5 points)
As a seller I want to be able to manage products in a form to add new products or modify existing products.

## Brief Description
Create a form to add new products or modify existing products.

## Feature Requirements
- Add form with fields for product properties
- Form fields have placeholders of the current product properties (obtained by product selection in Manage Products page)
   - These fields may be modified and saved
   - If the field is untouched, that product property will not change.
- Form posts updated product to database

### LINKED ISSUE #59: feature/seller-products
## User Story: (7 points)
As a seller I want to be able to view and edit my products because I want to modify my online inventory.

## Brief Description
Seller products table with ability to add, edit and delete products listed in it. (Edit and Add product buttons link to seller-product-form page)

## Feature Requirements
- seller table listing products with all their qualities
- buttons for adding, editing, and deleting products (buttons update database and link to form page if needed)

### PR DESCRIPTION
**Pull request by aspyridakos**
## Brief Description
Creating seller view products page and seller add products form. 

## Linked Issues
- closes #57 
- closes #59 

## Changes
- Added seller page with product table
- Added "Add product" button
   - Routes seller to form for adding new products
- Added "Modify product" button
   - Routes seller to form for modifying product
   - Automatically fills in product info to form

### CODE REVIEW

**Comment by Adamo-O** [comment]
I left `TODO` comments for parts that are waiting on future changes (especially backend).
These changes include:
- Modify product via database query
- Add new product via database query
- Create URL parameter from seller page to form page holding seller name
   - Use seller name in "Add new product" form via parameters (should show seller by default)
   - *Note*: This may require account management to be completed

**Comment by aspyridakos** [comment]
> I left `TODO` comments for parts that are waiting on future changes (especially backend). These changes include:
> 
> * Modify product via database query
> * Add new product via database query
> * Create URL parameter from seller page to form page holding seller name
>   
>   * Use seller name in "Add new product" form via parameters (should show seller by default)
>   * _Note_: This may require account management to be completed

Also missing:
- need a way to delete specific products from database when delete button is clicked by seller

**Comment by aspyridakos** [comment]
@Adamo-O I just added the last commit for my part of seller in this PR. Whenever you're ready ping someone from @SOEN-341-Project/frontend for an outside PR review.

**Comment by Adamo-O** [comment]
> @Adamo-O I just added the last commit for my part of seller in this PR. Whenever you're ready ping someone from @SOEN-341-Project/frontend for an outside PR review.

Should we wait for the backend changes to be done before completing the PR? If not, all the front end is done on my end!

**Comment by aspyridakos** [comment]
> > @Adamo-O I just added the last commit for my part of seller in this PR. Whenever you're ready ping someone from @SOEN-341-Project/frontend for an outside PR review.
> 
> 
> 
> Should we wait for the backend changes to be done before completing the PR? If not, all the front end is done on my end!

I would say to merge this part for now and we can make a separate PR to add the backend to all the pages. I think Emma will need our part for the navbar.

**Review by oumbarry — APPROVED** [review]
nice work!

**Review by ricks021 — COMMENTED** [review]
nice!

**Review by ricks021 — COMMENTED** [review]
nice

**Pull request merged**
