### PR TITLE
feature/login popup

### LINKED ISSUE #5: feature/login-functionality
## User Story: (5 points)
As a user I want to enter my login credentials through a login form because I would like to view my cart and my orders.

## Brief Description
The user should be able to enter their email address/username and password to sign in to their account. If they are not already registered, a sign up form should be displayed instead once "Not a member? Sign up here" link is clicked. Once signed in, navbar login button should become a logout button and user should be able to see a button called view my orders. 

## Feature Requirements
-  Login form which should display email/username input and password input:
     - email should be verified for correct format (ex: contains "@") 
     - password validity should be checked (is it associated to the provided username or email address)
     - Error messages should display if any validation errors are thrown or if no account associated to the given login credentials exists
     - "X" button at the top of the login form to close form popup or click away to close
     - Forgot password link (*optional*)
-  Login button to submit login form data should be at the bottom of the login form
-  "Not a member? Sign up here" link located at the bottom of the login for should take user to sign up form instead
- Login button of navbar should change to logout button and "view my orders" button should now be displayed in the navbar
- Sign up button should no longer be visible in navbar

# Additional context
Login form should look something like this:

image

### PR DESCRIPTION
**Pull request by aspyridakos**
## Brief Description
Added login popup as a clickable link from the navbar. This will allow users to sign in or link to register page to then access their cart and orders.

## Linked Issues
- closes #5 

## Changes
- added login popup to navbar
- added sign up button to navbar
- added temp sellers list to TestValues.json 
- added temp users list to TestValues.json
- installed jest using npm

## Acceptance Criteria
- [ ] Test coverage >80%
- [x] All specifications met in feature requirements

### CODE REVIEW

**Comment by Adamo-O** [comment]
Nice! Does this replace the current account icon? Or is it an addition?
Also should we have two separate buttons, one for login and one for sign up? We can keep the linking to the sign up in the login form, but signing up directly should be an option too

**Comment by aspyridakos** [comment]
> Nice! Does this replace the current account icon? Or is it an addition? Also should we have two separate buttons, one for login and one for sign up? We can keep the linking to the sign up in the login form, but signing up directly should be an option too

It's an addition to the account icon tab (some mods to the old code were required, but most is new stuff)

**Comment by aspyridakos** [comment]
Testing will be added upon navbar update completion in another PR. Otherwise should be good to approve.

**Review by jungsoolee1 — APPROVED** [review]
Looks fine!

**Pull request merged**
