### PR TITLE
feature/register-component

### PR DESCRIPTION
**Pull request by jungsoolee1**
## Brief Description
Created the register/signup component of the website.

## Changes
- Created the form allowing users to sign up their account
- Made email and password, and shipping address as required inputs
- Shipping address is split into different components (streetNb, streetName, city, province))
- Made seller name as a required input if user is a seller
- Optional inputs are first name, last name, username
- Input values are assigned to keys of the values object.

## Acceptance Criteria
- [ ] Test coverage >80%
- [ ] All specifications met in feature requirements

## Additional context
Adding the user data to the database is still to be determined.

### CODE REVIEW

**Comment by aspyridakos** [comment]
Don't forget to rebase with master. Looks good otherwise:)
Just need to test it locally before approving.

**Comment by aspyridakos** [comment]
Address should be split into multiple input fields (street & number, postal code, city, etc.)

**Review by aspyridakos — CHANGES_REQUESTED** [review]
Address should be split into multiple input fields (street & number, postal code, city, etc.)

**Comment by jungsoolee1** [comment]
Changed the address into multiple fields.

**Comment by aspyridakos** [comment]
Found a minor problem with the form. When using Google's autofill form data it expects to insert street number and street name on the same line rather than having them spread out into two input fields. 

Here's an example of how it autofilled an address (info is not actually where I live lol):
image

**Comment by aspyridakos** [comment]
Form field shows incorrect error:

image

Hyphens should be allowed since they are common in street names.

**Comment by aspyridakos** [comment]
No error is thrown when .com/.ca is missing:

image

**Comment by aspyridakos** [comment]
Password needs to check for a minimum number of characters and certain required symbols, numbers or letter cases.

**Review by aspyridakos — CHANGES_REQUESTED** [review]
Code is efficient and clear although some user requirements still haven't been met. Should be good to merge once these remaining issues I've left in comments have been addressed.

**Comment by jungsoolee1** [comment]
changed the password validation to require a strong password and changed the street name and street number to be combined together into one textfield

**Review by emma-amar — APPROVED** [review]
looks good to me!!

**Review by jungsoolee1 — COMMENTED** [review]
Fixed

**Review by aspyridakos — APPROVED** [review]
Solid PR💯

**Pull request merged**
