### PR TITLE
Added google storage key to online backend

### PR DESCRIPTION
**Pull request by KooshaG**
## Brief Description
It seems like uploading without the key broke for some reason, so I'm adding the key manually instead

## Changes
- Added uploading of google storage key to the backend

### CODE REVIEW

**Comment by aspyridakos** [comment]
Is this related to the stuff I broken on master? I'm wondering if it will go away when I revert changes.

**Review by Adamo-O — APPROVED** [review]
Looks good, let's get some images uploaded!

**Comment by KooshaG** [comment]
> Is this related to the stuff I broke on master? I'm wondering if it will go away when I revert changes.

No this is related to the uploading issue that for some reason came back. It was working for a while but now it broke again

**Comment by aspyridakos** [comment]
> > Is this related to the stuff I broke on master? I'm wondering if it will go away when I revert changes.
> 
> 
> 
> No this is related to the uploading issue that for some reason came back. It was working for a while but now it broke again

Ah ok gotcha.

**Review by Adamo-O — DISMISSED** [review]
Let's *actually* get images uploaded now!

**Review by aspyridakos — APPROVED** [review]
Looks good:)

**Review by Adamo-O — APPROVED** [review]
All looks good, nice mini refactoring too. Let's hope this all works!

**Pull request merged**
