### PR TITLE
Added SideNav product filtering

### LINKED ISSUE #30: feature/linking-sidenav-filters-to-product-display
## Brief Description
Sidenav filters should modify the product display grid to show/hide elements depending on set sidenav filter values.

## Feature Requirements
-  Filter by price range
- Filter by brand
- Filter by seller
- Show all products when no filters exist (reset filters button? --> optional)

### LINKED ISSUE #39: feature/replace-product-buttons-with-clickable-product-preview
## User Story: (2 points)
As a user I want to be able to easily select a product of interest to view more information and possibly add to cart.

## Brief Description
Removing product buttons and implementing clickable product preview.

## Feature Requirements
-  Remove product buttons
-  Make each product preview clickable

### PR DESCRIPTION
**Pull request by Adamo-O**
## Brief Description
Implemented slider price filtering and checkbox product filtering with visual updates.

## Linked Issues
- closes #30 
- closes #39 

## Changes
- Added ProductPage component as a parent to SideNav and ProductGrid
- Used 'lifting the state up' to make the handling methods available to parent components for encapsulation
- Added product filtering using filter and product states in ProductPage
- Used onCheckboxChange to handle checkbox filtering logic
- Use onSliderChange to handle product price filtering with slider

### Changes from PR #40 
- Removed product buttons (Add to Cart, View More)
- Used `<ButtonBase>` to make product preview clickable
   - Will route to product full page when routing is ready
- Increased font size of price
- Decreased font size of brands and sellers
- Used Stack component to vertically stack items
   - Stacked product information
- Put product image above product information for all screens
   - Product image stays above product information for all screen sizes, rather than lg or smaller
- Increased consistency when filtering data (less vertical movement and adjustments)
- Fixed h3 size
- Fixed padding
- Aligned all product images with static height

## Additional context
While the filter selection is optimized, the product rendering itself may be further optimized in the future if deemed necessary.

### CODE REVIEW

**Review by aspyridakos — APPROVED** [review]
@Adamo-O we should demo this for the team :) 

I haven't had the chance to test it locally yet but the code looks good as far as I can tell.

**Comment by aspyridakos** [comment]
Found a minor problem with the filtering. The seller of a brand should be automatically selected when one of the seller's brands are selected. Otherwise it won't display the products the user expects. I would suggest giving the user the option to either select by brand or by seller, not both. Alternatively, the brands and their associated sellers could be linked together in the checkbox dropdowns.

**Comment by aspyridakos** [comment]
Also shouldn't price filtering also be incorporated into this PR since it also has to do with filtering?

**Comment by Adamo-O** [comment]
> Found a minor problem with the filtering. The seller of a brand should be automatically selected when one of the seller's brands are selected. Otherwise it won't display the products the user expects. I would suggest giving the user the option to either select by brand or by seller, not both. Alternatively, the brands and their associated sellers could be linked together in the checkbox dropdowns.

The only reason why I didn't do that was because I was considering if some brands can be sold by different sellers. 
In that case, a seller may be selected that the user didn't mean. In my mind, brands and sellers weren't that closely related.

In reality, we can have one dropdown with some hierarchy, but that we should talk about since I'm not sure if it's necessary. I would rather make it generic and change it later if the need arises.

**Comment by Adamo-O** [comment]
> Also shouldn't price filtering be incorporated into this PR since it also has to do with filtering?

Yeah, we can include it here, but I might need you to help since I didn't get a good look at how the price numbering worked. I don't mind either way!

**Review by aspyridakos — APPROVED** [review]
Nice!🚀

**Pull request merged**
